stages:
 - update

updating:
 stage: update
 only:
   - tags
 tags:
   - ssh_update_ddk_nodes
 script:
   - $(kill $(screen -S update_ddk_nodes -Q echo '$PID')) || echo "No screen session found"
   - $(screen -wipe) || echo "No screen session found"
   - cd /home/provision/DDK.ORCHESTRATION.PROCESES/DDK.Delegat.Install.Environment/
   - screen -dmS update_ddk_nodes ./update.node.4rom.demo.on.all.targets.sh inventory.test.env
   - echo "running ..."
