stages:
 - build_core
 - start_core
 - auto_tests
 - build_core_tag
 - deploy-PREPROD
 - generate_docker-compose

build_core_tag_build:
  stage: build_core
  only:
    - master
  tags:
    - ddk-deploy
  script:
    - cd /root/DDK.Delegat.Install.Environment/
    - docker rmi ddkoin/core:build -f
    - ./build.tag.newcore.sh build master


deploy_STAGE:
 stage: start_core
 only:
   - master
 tags:
   - ddk-deploy
 script:
   - cd /root/DDK.Delegat.Install.Environment/
   - ansible-playbook -i ./inventory.newcore.skctestnet.env --limit SKC-TESTBUILD-CORE ./books/stop_docker_clean_volume.yml
   - ansible-playbook -i ./inventory.newcore.skctestnet.env --limit SKC-TESTBUILD-CORE ./books/clean_docker_image_core.yml
   - ansible-playbook -i ./inventory.newcore.skctestnet.env --limit SKC-TESTBUILD-CORE ./books/start_build_docker-compose.yml
   - ./manual.scripts/start.logs.stage.sh

auto_tests:
  stage: auto_tests
  only:
    - tags
  tags:
    - ddk-tests
  script:
    - /var/www/ddktest/auto_tests.sh

build_image_tag:
  stage: build_core_tag
  only:
    - tags
  tags:
    - ddk-deploy
  script:
    - cd /root/DDK.Delegat.Install.Environment/
    - ./build.tag.newcore.gitlab.sh

deploy_PREPROD_tag:
  stage: deploy-PREPROD
  only:
    - tags
  tags:
    - ddk-deploy
  script:
    - cd /var/ddk.builds/data/DDKCORE/
    - tag=$(git describe --tags $(git rev-list --tags --max-count=1))
    - cd /root/DDK.Delegat.Install.Environment/
    - ./refresh_and_generate_new_core.sh ./inventory.newcore.preprod.env 0.0.2 $tag development
    - cd /root/DDK.Delegat.Install.Environment/
    - ansible-playbook -i ./inventory.newcore.skctestnet.env --limit SKC-TESTNET ./books/update.docker.compose.yml
    - ./manual.scripts/start.logs.preprod.sh
    
deploy_PROD_last_tag:
  stage: generate_docker-compose
  when: manual
  tags:
    - ddk-deploy
  script:
    - cd /var/ddk.builds/data/DDKCORE/
    - tag=$(git describe --tags $(git rev-list --tags --max-count=1))
    - cd /root/DDK.Delegat.Install.Environment/
    - ./refresh_and_generate_new_core.sh ./inventory.newcore.prod.env 0.0.2 $tag mainnet
    - cd /root/DDK.Delegat.Install.Environment/
    - ansible-playbook -i ./inventory.newcore.prod.env --limit PROD-CORE ./books/update.docker.compose.yml
    - ./manual.scripts/start.logs.prod.sh
    
deploy_DELEGATES_last_tag:
  stage: generate_docker-compose
  when: manual
  tags:
    - ddk-deploy
  script:   
    - cd /var/ddk.builds/data/DDKCORE/
    - tag=$(git describe --tags $(git rev-list --tags --max-count=1))
    - cd /root/DDK.Delegat.Install.Environment/
    - ./refresh_and_generate_new_core.sh ./inventory.newcore.preprod.delegates.env 0.0.2 $tag testnet
    - cd /root/DDK.Delegat.Install.Environment/
    - ansible-playbook -i ./inventory.newcore.preprod.delegates.env ./books/update.docker.compose.yml
