stages:
 - build_core
 - start_core
 - build_core_tag
 - generate_docker-compose

build_core_tag_build:
  stage: build_core
  only:
    - master
  tags:
    - ddk-deploy
  script:
    - cd /root/DDK.Delegat.Install.Environment/
    - docker rmi ddkoin/core:build -f
    - ./build.tag.newcore.sh build master


deploy_STAGE:
 stage: start_core
 only:
   - master
 tags:
   - ddk-deploy
 script:
   - cd /root/DDK.Delegat.Install.Environment/
   - ansible-playbook -i ./inventory.newcore.skctestnet.env --limit SKC-STAGE-CORE ./books/stop.docker.containers.yml
   - ansible-playbook -i ./inventory.newcore.skctestnet.env --limit SKC-STAGE-CORE ./books/clean_docker_image_core.yml
   - ansible-playbook -i ./inventory.newcore.skctestnet.env --limit SKC-STAGE-CORE ./books/start.docker.containers.yml
   - ./manual.scripts/start.logs.stage.sh

deploy_LAB:
 stage: start_core
 only:
   - master
 tags:
   - ddk-deploy
 script:
   - cd /root/DDK.Delegat.Install.Environment/
   - ansible-playbook -i ./inventory.newcore.skctestnet.env --limit SKC-LAB-CORE ./books/stop_docker_clean_volume.yml
   - ansible-playbook -i ./inventory.newcore.skctestnet.env --limit SKC-LAB-CORE ./books/clean_docker_image_core.yml
   - ansible-playbook -i ./inventory.newcore.skctestnet.env --limit SKC-LAB-CORE ./books/start.docker.containers.yml
   - ./manual.scripts/start.logs.lab.sh

build_image_tag:
  stage: build_core_tag
  only:
    - tags
  tags:
    - ddk-deploy
  script:
    - cd /root/DDK.Delegat.Install.Environment/
    - ./build.tag.newcore.gitlab.sh

deploy_TEST_NODE_last_tag:
  stage: generate_docker-compose
  only:
    - tags
  tags:
    - ddk-deploy
  script:   
    - cd /var/ddk.builds/data/DDKCORE/
    - tag=$(git describe --tags $(git rev-list --tags --max-count=1))
    - cd /root/DDK.Delegat.Install.Environment/
    - ./refresh_and_generate_new_core.sh ./inventory.newcore.prod.env 0.0.2 $tag mainnet
    - cd /root/DDK.Delegat.Install.Environment/
    - ansible-playbook -i ./inventory.newcore.prod.env --limit TEST-NODE ./books/update.docker.compose.yml
    - ssh root@31.28.161.179 '~/tools/start.logs.sh'

deploy_DELEGATES_last_tag:
  stage: generate_docker-compose
  when: manual
  tags:
    - ddk-deploy
  script:   
    - cd /var/ddk.builds/data/DDKCORE/
    - tag=$(git describe --tags $(git rev-list --tags --max-count=1))
    - cd /root/DDK.Delegat.Install.Environment/
    - ./refresh_and_generate_new_core.sh ./inventory.newcore.preprod.delegates.env 0.0.2 $tag mainnet
    - cd /root/DDK.Delegat.Install.Environment/
    - ansible-playbook -i ./inventory.newcore.preprod.delegates.env ./books/update.docker.compose.yml
    - ./manual.scripts/start.logs.delegates.sh
