stages:
 - build_core
 - start_core

manual_build_core:
  stage: build_core
  only:
    - autodeploy-gitlab-tags
    - tags
  tags:
    - ddk-deploy
  script:
    - cd /root/DDK.Delegat.Install.Environment/
    - docker rmi ddkoin/core:$CI_COMMIT_TAG -f
    - ./build.tag.newcore.sh $CI_COMMIT_TAG autodeploy-gitlab-tags


updating:
 stage: start_core
 only:
   - autodeploy-gitlab-tags
 tags:
   - ddk-deploy
 script:
   - cd /root/DDK.Delegat.Install.Environment/
   - docker images
