stages:
 - build_core
 - start_core

build_image_tag:
  stage: build_core
  only:
    - tags
  tags:
    - ddk-deploy
  script:
    - cd /root/DDK.Delegat.Install.Environment/
    - ./build.tag.newcore.gitlab.sh


updating:
 stage: start_core
 only:
   - tags
 tags:
   - ddk-deploy
 script:
   - cd /root/DDK.Delegat.Install.Environment/
   - docker images
