FROM    node:8-alpine
RUN     apk add --no-cache python curl bash automake autoconf libtool git alpine-sdk postgresql-dev netcat-openbsd

USER    root
RUN     npm install --global npm@latest && \
        npm install --global node-gyp@latest && \
        npm install --global wait-port@latest

WORKDIR /home/ddk

COPY    docker-entrypoint.sh /home/ddk/docker-entrypoint.sh
RUN     chmod +x /home/ddk/docker-entrypoint.sh
CMD     ["/bin/bash", "/home/ddk/docker-entrypoint.sh"]
