export const GET_ACCOUNT = 'GET_ACCOUNT';
export const GET_ACCOUNT_BALANCE = 'GET_ACCOUNT_BALANCE';

export const GET_BLOCKS_HISTORY = 'GET_BLOCKS_HISTORY';
export const GET_BLOCK_BY_ID = 'GET_BLOCK_BY_ID';

export const GET_ACTIVE_DELEGATES = 'GET_ACTIVE_DELEGATES';
export const GET_INACTIVE_DELEGATES = 'GET_INACTIVE_DELEGATES';

export const GET_REFERRED_USERS = 'GET_REFERRED_USERS';
export const GET_REFERRED_USERS_BY_LEVEL = 'GET_REFERRED_USERS_BY_LEVEL';

export const GET_REWARD_HISTORY = 'GET_REWARD_HISTORY';
export const GET_REFERRED_USERS_REWARD = 'GET_REFERRED_USERS_REWARDS';

export const GET_CURRENT_ROUND = 'GET_CURRENT_ROUND';

export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const GET_TRANSACTION = 'GET_TRANSACTION';
export const GET_TRANSACTION_BY_ID = 'GET_TRANSACTION_BY_ID';
export const GET_TRANSACTION_HISTORY = 'GET_TRANSACTION_HISTORY';
export const GET_TRANSACTIONS_BY_BLOCK_ID = 'GET_TRANSACTIONS_BY_BLOCK_ID';
