export enum ActionTypes {
    BLOCK_GENERATE = 'BLOCK_GENERATE',
    ROUND_FINISH = 'ROUND_FINISH',
    EMIT_REBOOT_PEERS_CONNECTIONS = 'EMIT_REBOOT_PEERS_CONNECTIONS',
    BLOCK_RECEIVE = 'BLOCK_RECEIVE',
    TRANSACTION_RECEIVE = 'TRANSACTION_RECEIVE',
}
